### ISSUE TITLE
用不来。。。。。。

### ISSUE THREAD

**Issue by freejacklee** [reycn/deepl-custom-server-for-bob#1]
如题

**Comment by freejacklee** [comment]
python3.7 

Macos12.4

pip3 install loguru

pip3 install sanic

pip3 install sentry_sdk

pip3 install pyppeteer

终端执行 python3 main.py

报错

➜  deepl-custom-server-for-bob-main python3 main.py
2022-07-10 09:51:44.033 | ERROR    | __main__:<module>:21 - Init:No section: 'sentry'
Traceback (most recent call last):

> File "main.py", line 18, in <module>
    sentry = cfg.get('sentry', 'sdk')
             │   └ <function RawConfigParser.get at 0x7faa1ec98b00>
             └ <configparser.ConfigParser object at 0x7faa1ef61e10>

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
        │    │             │        └ None
        │    │             └ 'sentry'
        │    └ <function RawConfigParser._unify_values at 0x7faa1ec99950>
        └ <configparser.ConfigParser object at 0x7faa1ef61e10>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
          │              └ 'sentry'
          └ <class 'configparser.NoSectionError'>

configparser.NoSectionError: No section: 'sentry'

怀疑：main.py中的代码  cfg.read(path)      path需要改下

try:
    cfg = ConfigParser()
    cfg.read(path)
    sentry = cfg.get('sentry', 'sdk')
    init(sentry, traces_sample_rate=1.0)
except Exception as e:
    logger.exception("Init:" + str(e))
    capture_message('Init: ' + str(e))
    exit()

**Comment by freejacklee** [comment]
@reycn 求大佬赐教

**Comment by freejacklee** [comment]
本地位置 '/Users/yujunhao/Downloads/deepl-custom-server-for-bob-main/'

**Comment by reycn** [comment]
不做技术支持；因为一些原因刻意没有提供使用说明敬请谅解。

**Comment by freejacklee** [comment]
@reycn 好的，没关系
